/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
    winTrigger: THREE.Mesh
  }
  materials: {
    Grass: THREE.MeshStandardMaterial
    Wood: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/holeOneColliders.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name='Cube' geometry={nodes.Cube.geometry} material={materials.Grass} />
      <mesh name='Cube001' geometry={nodes.Cube001.geometry} material={materials.Grass} />
      <mesh name='Cube002' geometry={nodes.Cube002.geometry} material={materials.Grass} />
      <mesh
        name='Cube003'
        geometry={nodes.Cube003.geometry}
        material={materials.Wood}
        position={[-1.08, 0.17, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        name='Cube004'
        geometry={nodes.Cube004.geometry}
        material={materials.Wood}
        position={[-1.08, 0.17, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        name='Cube005'
        geometry={nodes.Cube005.geometry}
        material={materials.Wood}
        position={[-1.08, 0.17, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        name='Cube006'
        geometry={nodes.Cube006.geometry}
        material={materials.Wood}
        position={[1.09, 0.17, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        name='Cube007'
        geometry={nodes.Cube007.geometry}
        material={materials.Wood}
        position={[1.09, 0.17, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        name='Cube008'
        geometry={nodes.Cube008.geometry}
        material={materials.Wood}
        position={[1.09, 0.17, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        name='Cube009'
        geometry={nodes.Cube009.geometry}
        material={materials.Wood}
        position={[0, 0.17, -3.08]}
        scale={[1.2, 0.1, 0.1]}
      />
      <mesh
        name='Cube010'
        geometry={nodes.Cube010.geometry}
        material={materials.Wood}
        position={[0, 2.46, 14.26]}
        scale={[1.2, 0.1, 0.1]}
      />
      <mesh
        name='winTrigger'
        geometry={nodes.winTrigger.geometry}
        material={nodes.winTrigger.material}
        position={[0, 2.13, 13.43]}
        scale={[0.47, 1, 0.15]}
      />
    </group>
  )
}

useGLTF.preload('/holeOneColliders.glb')
