/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Cube010: THREE.Mesh
  }
  materials: {}
}

export function TestRamp(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/testRamp.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-1.08, 0.17, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[-1.08, 0.17, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-1.08, 0.17, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[1.09, 0.17, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[1.09, 0.17, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[1.09, 0.17, 0]}
        scale={[0.1, 1, 1]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[0, 0.17, -3.08]}
        scale={[1.2, 0.1, 0.1]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[0, 2.46, 14.26]}
        scale={[1.2, 0.1, 0.1]}
      />
    </group>
  )
}

useGLTF.preload('/testRamp.glb')
